import { db } from "@/db";
import { adminAuditLog } from "@/db/schema";

/**
 * Builds an admin-audit-log insert and returns the (already-awaitable) query builder so callers can
 * either `await` it directly for a standalone log entry, or fire it alongside other writes.
 *
 * Note on atomicity: the neon-http Postgres driver used by this project (see db/index.ts) does not
 * support interactive `db.transaction(...)` — calling it throws "No transactions support in
 * neon-http driver" at runtime. All multi-statement admin writes in this codebase (product + variant
 * creation, order status transitions, etc.) therefore use plain sequential `await`s rather than a
 * real transaction. IDs needed by a dependent write are generated by the database (uuid default) and
 * read back via `.returning()` before the next statement runs. This is a known gap versus the task's
 * "use db.transaction for multi-table writes" guidance — a genuinely atomic multi-statement path would
 * require switching db/index.ts to the `neon-serverless` (Pool-based) driver, which is out of scope
 * for this change since db/index.ts is shared, already-built infrastructure.
 */
export function auditLogEntry(params: {
  actorEmail: string;
  action: string;
  entityType?: string;
  entityId?: string;
  detail?: unknown;
}) {
  return db.insert(adminAuditLog).values({
    actorEmail: params.actorEmail,
    action: params.action,
    entityType: params.entityType,
    entityId: params.entityId,
    detail: params.detail === undefined ? null : JSON.stringify(params.detail),
  });
}
